### PR TITLE
Add batch support and use Cloudinary API v2

### PR DESCRIPTION
**Pull request by pvhee**
* Add batch support so you can download more than 500 images (pagination limit from Cloudinary) in one go
* Use Cloudinary API v2 so you can pass in cursor options

### CODE REVIEW

**Comment by pvhee** [comment]
@hanford thought these were useful additions, in order to export more than 500 images from Cloudinary

**Comment by hanford** [comment]
Wow, awesome! 🎉

**Comment by hanford** [comment]
@pvhee will I need to install a new version of cloudinary's api in the `package.json`?

**Comment by pvhee** [comment]
@hanford `v2` is part of the `cloudinary` package since quite some years now it seems, and worked with the version you specify in `package.json`, so no need.

thanks for merging!

**Pull request merged**
